// <auto-generated />
namespace INEEL.DataAccess.GEN.MigrationsCR
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OportunidadNegocio00001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OportunidadNegocio00001));
        
        string IMigrationMetadata.Id
        {
            get { return "201609231624122_OportunidadNegocio00001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
