// <auto-generated />
namespace INEEL.DataAccess.GEN.MigrationsCR
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TBLSEGUIMIENTOMarco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TBLSEGUIMIENTOMarco));
        
        string IMigrationMetadata.Id
        {
            get { return "201611302154541_TBL-SEGUIMIENTO-Marco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
