// <auto-generated />
namespace INEEL.DataAccess.GEN.MigrationsCR
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class camposMarcON : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(camposMarcON));
        
        string IMigrationMetadata.Id
        {
            get { return "201612062331434_camposMarcON"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
