// <auto-generated />
namespace INEEL.DataAccess.GEN.MigrationsCR
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class QuitaContactoFondos2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuitaContactoFondos2));
        
        string IMigrationMetadata.Id
        {
            get { return "201706132007595_QuitaContactoFondos2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
