// <auto-generated />
namespace INEEL.DataAccess.GEN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MigracionJWIR18JUL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigracionJWIR18JUL));
        
        string IMigrationMetadata.Id
        {
            get { return "201607181830318_MigracionJWIR18JUL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
