// <auto-generated />
namespace INEEL.DataAccess.GEN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ESTRUCTURA121 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ESTRUCTURA121));
        
        string IMigrationMetadata.Id
        {
            get { return "201607211729514_ESTRUCTURA121"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
