// <auto-generated />
namespace INEEL.DataAccess.GEN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PersonalProyecto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonalProyecto));
        
        string IMigrationMetadata.Id
        {
            get { return "201608221917521_PersonalProyecto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
