// <auto-generated />
namespace INEEL.DataAccess.GEN.MigrationsPI
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migraProyectFactPI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migraProyectFactPI));
        
        string IMigrationMetadata.Id
        {
            get { return "201702231958283_migraProyectFactPI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
