// <auto-generated />
namespace INEEL.DataAccess.GEN.MigrationsCH
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AJUSTERELACIONCOMPETENCIANIVEL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AJUSTERELACIONCOMPETENCIANIVEL));
        
        string IMigrationMetadata.Id
        {
            get { return "201703141705332_AJUSTERELACIONCOMPETENCIANIVEL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
