// <auto-generated />
namespace INEEL.DataAccess.GEN.MigrationsMT
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class solicitudRevisionITF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(solicitudRevisionITF));
        
        string IMigrationMetadata.Id
        {
            get { return "201608271829224_solicitudRevisionITF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
