// <auto-generated />
namespace INEEL.DataAccess.GEN.MigrationsGI
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migGIComunes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migGIComunes));
        
        string IMigrationMetadata.Id
        {
            get { return "201708041525133_migGIComunes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
