// <auto-generated />
namespace INEEL.DataAccess.GEN.MigrationsGI
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migempresaint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migempresaint));
        
        string IMigrationMetadata.Id
        {
            get { return "201707261936028_migempresaint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
