// <auto-generated />
namespace INEEL.DataAccess.GEN.MigrationsGI
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migBitacoraFI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migBitacoraFI));
        
        string IMigrationMetadata.Id
        {
            get { return "201708221434528_migBitacoraFI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
